#./docker-compose.yml
#https://ilhub.io/blog/2019/05/30/vscode-remote
version: '3.7'

services:
  postgres:
    image: postgres:11.3-alpine
    container_name: vscode_remote_postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./docker/data/postgres:/var/lib/postgres/data
  app:
    build:
      context: ./docker/dev
      dockerfile: Dockerfile
    container_name: vscode_remote_app
    ports:
      - 8000:8000
      - 3000:3000
    volumes:
      - .:/workspace
      - ~/.ssh:/root/.ssh
    command: sleep infinity
    depends_on:
      - postgres